-- GENERATED by test/helpers/fake_server_parity_test.dart. Do not edit:
-- change the script or the fake there, then write this file again with
--   MEDORA_WRITE_PARITY_SQL=1 fvm flutter test test/helpers/fake_server_parity_test.dart
--
-- The same writes the test sends to the fake server, each followed by the
-- rows the fake held afterwards. Run by tools/check_supabase_sql.sh after
-- every migration: any row where Postgres differs from the fake stops it.
-- `@<step>` is the time that step arrived (its now()).
\set ON_ERROR_STOP on

create temp table parity_now (step int primary key, at timestamptz not null);

create function pg_temp.parity_time(t timestamptz) returns text language sql as $$
  select case when t is null then null else coalesce(
    (select '@' || step from parity_now where at = t order by step desc limit 1),
    to_char(t at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) end
$$;

create function pg_temp.parity_row(p_table text, p_id text) returns jsonb
language plpgsql as $$
declare
  r jsonb;
  m jsonb := '{}';
  k text;
begin
  execute format('select to_jsonb(t) from public.%I t where id = $1', p_table)
    into r using p_id;
  for k in select jsonb_object_keys(r->'field_edited_at') loop
    m := m || jsonb_build_object(k, jsonb_build_object(
      'at', pg_temp.parity_time((r->'field_edited_at'->k->>'at')::timestamptz),
      'auto', r->'field_edited_at'->k->'auto'));
  end loop;
  return jsonb_build_object(
    'row_version', r->'row_version',
    'write_id', r->>'write_id' is not null,
    'edited_at', pg_temp.parity_time((r->>'edited_at')::timestamptz),
    'updated_at', pg_temp.parity_time((r->>'updated_at')::timestamptz),
    'deleted', r->>'deleted_at' is not null,
    'field_edited_at', m);
end
$$;

-- Step 0: 0.3.0 creates a treatment naming three columns: an empty map
begin;
insert into parity_now values (0, now());
insert into public.treatments (id, name, start_date, updated_at)
  values ('par-t1', 'Flu', '2020-01-01', '2020-01-01T00:00:00.000Z')
  on conflict (id) do update set name = excluded.name, start_date = excluded.start_date, updated_at = excluded.updated_at;
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":false,"edited_at":"2020-01-01T00:00:00.000Z","field_edited_at":{},"row_version":1,"updated_at":"@0","write_id":false}'::jsonb,
    format('parity step 0, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
end $$;

-- Step 1: a 0.4.0 device changes the doctor: the first update fills every other column, named or not, with the row time
begin;
insert into parity_now values (1, now());
update public.treatments set doctor = 'Dr. A', write_id = '00000000-0000-0000-0000-000000000001', edited_at = '2020-02-01T00:00:00.000Z', field_edited_at = '{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t1';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":false,"edited_at":"2020-02-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false},"end_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"family_id":{"at":"2020-01-01T00:00:00.000Z","auto":false},"is_active":{"at":"2020-01-01T00:00:00.000Z","auto":false},"name":{"at":"2020-01-01T00:00:00.000Z","auto":false},"notes":{"at":"2020-01-01T00:00:00.000Z","auto":false},"patient_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_from":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_to":{"at":"2020-01-01T00:00:00.000Z","auto":false},"start_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"symptom_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false}},"row_version":2,"updated_at":"@1","write_id":true}'::jsonb,
    format('parity step 1, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
end $$;

-- Step 2: 0.3.0 sends the row again with notes: only notes is stamped, on arrival
begin;
insert into parity_now values (2, now());
insert into public.treatments (id, name, start_date, notes, updated_at)
  values ('par-t1', 'Flu', '2020-01-01', 'n', '2020-01-01T00:00:00.000Z')
  on conflict (id) do update set name = excluded.name, start_date = excluded.start_date, notes = excluded.notes, updated_at = excluded.updated_at;
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":false,"edited_at":"@2","field_edited_at":{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false},"end_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"family_id":{"at":"2020-01-01T00:00:00.000Z","auto":false},"is_active":{"at":"2020-01-01T00:00:00.000Z","auto":false},"name":{"at":"2020-01-01T00:00:00.000Z","auto":false},"notes":{"at":"@2","auto":false},"patient_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_from":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_to":{"at":"2020-01-01T00:00:00.000Z","auto":false},"start_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"symptom_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false}},"row_version":3,"updated_at":"@2","write_id":false}'::jsonb,
    format('parity step 2, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
end $$;

-- Step 3: a 0.4.0 write, then one repeating its write id: that one is legacy and its map is not read
begin;
insert into parity_now values (3, now());
update public.treatments set sick_leave_ref = 'R1', write_id = '00000000-0000-0000-0000-000000000002', edited_at = '2020-03-01T00:00:00.000Z', field_edited_at = '{"sick_leave_ref":{"at":"2020-03-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t1';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":false,"edited_at":"2020-03-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false},"end_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"family_id":{"at":"2020-01-01T00:00:00.000Z","auto":false},"is_active":{"at":"2020-01-01T00:00:00.000Z","auto":false},"name":{"at":"2020-01-01T00:00:00.000Z","auto":false},"notes":{"at":"@2","auto":false},"patient_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_from":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-03-01T00:00:00.000Z","auto":false},"sick_leave_to":{"at":"2020-01-01T00:00:00.000Z","auto":false},"start_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"symptom_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false}},"row_version":4,"updated_at":"@3","write_id":true}'::jsonb,
    format('parity step 3, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
end $$;

-- Step 4: the repeated write id
begin;
insert into parity_now values (4, now());
update public.treatments set sick_leave_ref = 'R2', write_id = '00000000-0000-0000-0000-000000000002', edited_at = '2020-03-01T00:00:00.000Z', field_edited_at = '{"sick_leave_ref":{"at":"2020-01-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t1';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":false,"edited_at":"@4","field_edited_at":{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false},"end_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"family_id":{"at":"2020-01-01T00:00:00.000Z","auto":false},"is_active":{"at":"2020-01-01T00:00:00.000Z","auto":false},"name":{"at":"2020-01-01T00:00:00.000Z","auto":false},"notes":{"at":"@2","auto":false},"patient_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_from":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"@4","auto":false},"sick_leave_to":{"at":"2020-01-01T00:00:00.000Z","auto":false},"start_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"symptom_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false}},"row_version":5,"updated_at":"@4","write_id":false}'::jsonb,
    format('parity step 4, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
end $$;

-- Step 5: 0.4.0 inserts with times: one kept, a future one capped, an early one automatic, bookkeeping and unknown keys dropped
begin;
insert into parity_now values (5, now());
insert into public.treatments (id, name, start_date, notes, doctor, sick_leave_ref, write_id, edited_at, field_edited_at)
  values ('par-t2', 'Cold', '2020-03-01', 'x', 'D', 'R', '00000000-0000-0000-0000-000000000003', '2020-03-01T00:00:00.000Z', '{"name":{"at":"2020-03-01T00:00:00.000Z","auto":false},"notes":{"at":"2099-01-01T00:00:00.000Z","auto":false},"doctor":{"at":"1970-01-01T00:00:00.500Z","auto":false},"updated_at":{"at":"2020-03-01T00:00:00.000Z","auto":false},"no_such_column":{"at":"2020-03-01T00:00:00.000Z","auto":false}}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"2020-03-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"name":{"at":"2020-03-01T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":false}},"row_version":1,"updated_at":"@5","write_id":true}'::jsonb,
    format('parity step 5, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 6: an automatic change keeps the time, and updated_at
begin;
insert into parity_now values (6, now());
update public.treatments set notes = 'auto', write_id = '00000000-0000-0000-0000-000000000004', edited_at = '1970-01-01T00:00:00.000Z', field_edited_at = '{"notes":{"at":"1970-01-01T00:00:00.000Z","auto":true}}'::jsonb
  where id = 'par-t2';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"name":{"at":"2020-03-01T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":true}},"row_version":2,"updated_at":"@5","write_id":true}'::jsonb,
    format('parity step 6, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 7: one write: a column with its own time, one flagged automatic, one with no time (the row time), and a later person's entry for an unchanged column, which moves it
begin;
insert into parity_now values (7, now());
update public.treatments set name = 'Cold', end_date = '2020-03-05', is_active = false, sick_leave_from = '2020-03-02', write_id = '00000000-0000-0000-0000-000000000005', edited_at = '2020-03-04T00:00:00.000Z', field_edited_at = '{"name":{"at":"2020-03-09T00:00:00.000Z","auto":false},"end_date":{"at":"2020-03-03T00:00:00.000Z","auto":true},"is_active":{"at":"2020-03-02T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t2';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"2020-03-04T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"end_date":{"at":"1970-01-01T00:00:00.000Z","auto":true},"is_active":{"at":"2020-03-02T00:00:00.000Z","auto":false},"name":{"at":"2020-03-09T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":true},"sick_leave_from":{"at":"2020-03-04T00:00:00.000Z","auto":false}},"row_version":3,"updated_at":"@7","write_id":true}'::jsonb,
    format('parity step 7, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 8: the same values again: an older entry and an automatic one for unchanged columns are ignored
begin;
insert into parity_now values (8, now());
update public.treatments set name = 'Cold', is_active = false, sick_leave_ref = 'R2', write_id = '00000000-0000-0000-0000-000000000090', edited_at = '2020-03-10T00:00:00.000Z', field_edited_at = '{"name":{"at":"2020-03-08T00:00:00.000Z","auto":false},"is_active":{"at":"2020-03-10T00:00:00.000Z","auto":true},"sick_leave_ref":{"at":"2020-03-10T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t2';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"2020-03-10T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"end_date":{"at":"1970-01-01T00:00:00.000Z","auto":true},"is_active":{"at":"2020-03-02T00:00:00.000Z","auto":false},"name":{"at":"2020-03-09T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":true},"sick_leave_from":{"at":"2020-03-04T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-03-10T00:00:00.000Z","auto":false}},"row_version":4,"updated_at":"@8","write_id":true}'::jsonb,
    format('parity step 8, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 9: the automatic value again with an older person's time: the automatic entry stays
begin;
insert into parity_now values (9, now());
update public.treatments set notes = 'auto', write_id = '00000000-0000-0000-0000-000000000091', edited_at = '2020-02-01T00:00:00.000Z', field_edited_at = '{"notes":{"at":"2020-02-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t2';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"2020-02-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"end_date":{"at":"1970-01-01T00:00:00.000Z","auto":true},"is_active":{"at":"2020-03-02T00:00:00.000Z","auto":false},"name":{"at":"2020-03-09T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":true},"sick_leave_from":{"at":"2020-03-04T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-03-10T00:00:00.000Z","auto":false}},"row_version":5,"updated_at":"@9","write_id":true}'::jsonb,
    format('parity step 9, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 10: a person's older time never replaces the held one, and clears the automatic flag
begin;
insert into parity_now values (10, now());
update public.treatments set notes = 'older', write_id = '00000000-0000-0000-0000-000000000006', edited_at = '2020-02-01T00:00:00.000Z', field_edited_at = '{"notes":{"at":"2020-02-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-t2';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t2') = '{"deleted":false,"edited_at":"2020-02-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"1970-01-01T00:00:00.000Z","auto":true},"end_date":{"at":"1970-01-01T00:00:00.000Z","auto":true},"is_active":{"at":"2020-03-02T00:00:00.000Z","auto":false},"name":{"at":"2020-03-09T00:00:00.000Z","auto":false},"notes":{"at":"@5","auto":false},"sick_leave_from":{"at":"2020-03-04T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"2020-03-10T00:00:00.000Z","auto":false}},"row_version":6,"updated_at":"@10","write_id":true}'::jsonb,
    format('parity step 10, treatments/par-t2: postgres %s', pg_temp.parity_row('treatments', 'par-t2'));
end $$;

-- Step 11: 0.3.0 creates a medication
begin;
insert into parity_now values (11, now());
insert into public.medications (id, name, quantity)
  values ('par-m1', 'Ibuprofen', 10)
  on conflict (id) do update set name = excluded.name, quantity = excluded.quantity;
commit;
do $$ begin
  assert pg_temp.parity_row('medications', 'par-m1') = '{"deleted":false,"edited_at":"@11","field_edited_at":{},"row_version":1,"updated_at":"@11","write_id":false}'::jsonb,
    format('parity step 11, medications/par-m1: postgres %s', pg_temp.parity_row('medications', 'par-m1'));
end $$;

-- Step 12: 0.3.0 creates a prescription
begin;
insert into parity_now values (12, now());
insert into public.prescriptions (id, treatment_id, medication_id, dosage, start_time)
  values ('par-p1', 'par-t1', 'par-m1', '1 tablet', '2020-01-01T08:00:00.000Z')
  on conflict (id) do update set treatment_id = excluded.treatment_id, medication_id = excluded.medication_id, dosage = excluded.dosage, start_time = excluded.start_time;
commit;
do $$ begin
  assert pg_temp.parity_row('prescriptions', 'par-p1') = '{"deleted":false,"edited_at":"@12","field_edited_at":{},"row_version":1,"updated_at":"@12","write_id":false}'::jsonb,
    format('parity step 12, prescriptions/par-p1: postgres %s', pg_temp.parity_row('prescriptions', 'par-p1'));
end $$;

-- Step 13: 0.4.0 inserts a generated dose: automatic, updated_at kept
begin;
insert into parity_now values (13, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, updated_at, write_id, edited_at, field_edited_at)
  values ('par-d1', 'par-p1', '2020-01-01T08:00:00.000Z', 'pending', '1970-01-01T00:00:00.000Z', '00000000-0000-0000-0000-000000000007', '1970-01-01T00:00:00.000Z', '{}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d1') = '{"deleted":false,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{},"row_version":1,"updated_at":"1970-01-01T00:00:00.000Z","write_id":true}'::jsonb,
    format('parity step 13, dose_logs/par-d1: postgres %s', pg_temp.parity_row('dose_logs', 'par-d1'));
end $$;

-- Step 14: a person takes it: the fill marks the untouched columns automatic
begin;
insert into parity_now values (14, now());
update public.dose_logs set status = 'taken', taken_time = '2020-04-01T00:00:00.000Z', write_id = '00000000-0000-0000-0000-000000000008', edited_at = '2020-04-01T00:00:00.000Z', field_edited_at = '{"status":{"at":"2020-04-01T00:00:00.000Z","auto":false},"taken_time":{"at":"2020-04-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-d1';
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d1') = '{"deleted":false,"edited_at":"2020-04-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"1970-01-01T00:00:00.000Z","auto":true},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"2020-04-01T00:00:00.000Z","auto":false},"taken_time":{"at":"2020-04-01T00:00:00.000Z","auto":false}},"row_version":2,"updated_at":"@14","write_id":true}'::jsonb,
    format('parity step 14, dose_logs/par-d1: postgres %s', pg_temp.parity_row('dose_logs', 'par-d1'));
end $$;

-- Step 15: 0.4.0 inserts a second generated dose
begin;
insert into parity_now values (15, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, updated_at, write_id, edited_at, field_edited_at)
  values ('par-d2', 'par-p1', '2020-01-01T16:00:00.000Z', 'pending', '1970-01-01T00:00:00.000Z', '00000000-0000-0000-0000-000000000009', '1970-01-01T00:00:00.000Z', '{}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":false,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{},"row_version":1,"updated_at":"1970-01-01T00:00:00.000Z","write_id":true}'::jsonb,
    format('parity step 15, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 16: a stock change leaves the map alone
begin;
insert into parity_now values (16, now());
update public.medications set quantity = 9, write_id = '00000000-0000-0000-0000-000000000010'
  where id = 'par-m1';
commit;
do $$ begin
  assert pg_temp.parity_row('medications', 'par-m1') = '{"deleted":false,"edited_at":"@11","field_edited_at":{"active_ingredients":{"at":"@11","auto":false},"atc_code":{"at":"@11","auto":false},"barcode":{"at":"@11","auto":false},"category":{"at":"@11","auto":false},"description":{"at":"@11","auto":false},"ean":{"at":"@11","auto":false},"expiry_date":{"at":"@11","auto":false},"family_id":{"at":"@11","auto":false},"form":{"at":"@11","auto":false},"image_path":{"at":"@11","auto":false},"is_archived":{"at":"@11","auto":false},"manufacturer":{"at":"@11","auto":false},"minimum_stock_level":{"at":"@11","auto":false},"name":{"at":"@11","auto":false},"notes":{"at":"@11","auto":false},"patient_tags":{"at":"@11","auto":false},"purchase_date":{"at":"@11","auto":false},"quantity_unit":{"at":"@11","auto":false},"storage_location":{"at":"@11","auto":false},"symptoms":{"at":"@11","auto":false}},"row_version":2,"updated_at":"@16","write_id":true}'::jsonb,
    format('parity step 16, medications/par-m1: postgres %s', pg_temp.parity_row('medications', 'par-m1'));
end $$;

-- Step 17: the schedule drops the second dose: the app's own tombstone
begin;
insert into parity_now values (17, now());
update public.dose_logs set deleted_at = '2020-04-01T00:00:00.000Z', write_id = '00000000-0000-0000-0000-000000000011', edited_at = '1970-01-01T00:00:00.000Z'
  where id = 'par-d2';
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"1970-01-01T00:00:00.000Z","auto":true},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"1970-01-01T00:00:00.000Z","auto":true},"taken_time":{"at":"1970-01-01T00:00:00.000Z","auto":true}},"row_version":2,"updated_at":"1970-01-01T00:00:00.000Z","write_id":true}'::jsonb,
    format('parity step 17, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 18: 0.3.0 re-sends the dropped dose with a note: still the app's tombstone
begin;
insert into parity_now values (18, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, notes, updated_at)
  values ('par-d2', 'par-p1', '2020-01-01T16:00:00.000Z', 'pending', 'n', '2020-04-01T00:00:00.000Z')
  on conflict (id) do update set prescription_id = excluded.prescription_id, scheduled_time = excluded.scheduled_time, status = excluded.status, notes = excluded.notes, updated_at = excluded.updated_at;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"@18","auto":false},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"1970-01-01T00:00:00.000Z","auto":true},"taken_time":{"at":"1970-01-01T00:00:00.000Z","auto":true}},"row_version":3,"updated_at":"@18","write_id":false}'::jsonb,
    format('parity step 18, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 19: 0.3.0 takes the dropped dose: it comes back as a person's change
begin;
insert into parity_now values (19, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, taken_time, notes, updated_at)
  values ('par-d2', 'par-p1', '2020-01-01T16:00:00.000Z', 'taken', '2020-04-01T00:00:00.000Z', 'n', '2020-04-01T00:00:00.000Z')
  on conflict (id) do update set prescription_id = excluded.prescription_id, scheduled_time = excluded.scheduled_time, status = excluded.status, taken_time = excluded.taken_time, notes = excluded.notes, updated_at = excluded.updated_at;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":false,"edited_at":"@19","field_edited_at":{"notes":{"at":"@18","auto":false},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"@19","auto":false},"taken_time":{"at":"@19","auto":false}},"row_version":4,"updated_at":"@19","write_id":false}'::jsonb,
    format('parity step 19, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 20: a person deletes the treatment: the tombstone cascades to the prescription and its doses as the app's own change
begin;
insert into parity_now values (20, now());
update public.treatments set deleted_at = '2020-05-01T00:00:00.000Z', write_id = '00000000-0000-0000-0000-000000000012', edited_at = '2020-05-01T00:00:00.000Z'
  where id = 'par-t1';
commit;
do $$ begin
  assert pg_temp.parity_row('treatments', 'par-t1') = '{"deleted":true,"edited_at":"2020-05-01T00:00:00.000Z","field_edited_at":{"doctor":{"at":"2020-02-01T00:00:00.000Z","auto":false},"end_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"family_id":{"at":"2020-01-01T00:00:00.000Z","auto":false},"is_active":{"at":"2020-01-01T00:00:00.000Z","auto":false},"name":{"at":"2020-01-01T00:00:00.000Z","auto":false},"notes":{"at":"@2","auto":false},"patient_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_from":{"at":"2020-01-01T00:00:00.000Z","auto":false},"sick_leave_ref":{"at":"@4","auto":false},"sick_leave_to":{"at":"2020-01-01T00:00:00.000Z","auto":false},"start_date":{"at":"2020-01-01T00:00:00.000Z","auto":false},"symptom_tags":{"at":"2020-01-01T00:00:00.000Z","auto":false}},"row_version":6,"updated_at":"@20","write_id":true}'::jsonb,
    format('parity step 20, treatments/par-t1: postgres %s', pg_temp.parity_row('treatments', 'par-t1'));
  assert pg_temp.parity_row('prescriptions', 'par-p1') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"auto_diminish":{"at":"@12","auto":false},"dosage":{"at":"@12","auto":false},"dosage_amount":{"at":"@12","auto":false},"dosage_unit":{"at":"@12","auto":false},"duration_days":{"at":"@12","auto":false},"interval_hours":{"at":"@12","auto":false},"is_active":{"at":"@12","auto":false},"medication_id":{"at":"@12","auto":false},"notes":{"at":"@12","auto":false},"schedule_times":{"at":"@12","auto":false},"schedule_type":{"at":"@12","auto":false},"start_time":{"at":"@12","auto":false},"treatment_id":{"at":"@12","auto":false}},"row_version":2,"updated_at":"@20","write_id":false}'::jsonb,
    format('parity step 20, prescriptions/par-p1: postgres %s', pg_temp.parity_row('prescriptions', 'par-p1'));
  assert pg_temp.parity_row('dose_logs', 'par-d1') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"1970-01-01T00:00:00.000Z","auto":true},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"2020-04-01T00:00:00.000Z","auto":false},"taken_time":{"at":"2020-04-01T00:00:00.000Z","auto":false}},"row_version":3,"updated_at":"@20","write_id":false}'::jsonb,
    format('parity step 20, dose_logs/par-d1: postgres %s', pg_temp.parity_row('dose_logs', 'par-d1'));
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"@18","auto":false},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"@19","auto":false},"taken_time":{"at":"@19","auto":false}},"row_version":5,"updated_at":"@20","write_id":false}'::jsonb,
    format('parity step 20, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 21: a device that has not heard of it sends a generated dose: stored deleted
begin;
insert into parity_now values (21, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, updated_at, write_id, edited_at, field_edited_at)
  values ('par-d3', 'par-p1', '2020-01-02T08:00:00.000Z', 'pending', '1970-01-01T00:00:00.000Z', '00000000-0000-0000-0000-000000000013', '1970-01-01T00:00:00.000Z', '{}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d3') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{},"row_version":1,"updated_at":"1970-01-01T00:00:00.000Z","write_id":true}'::jsonb,
    format('parity step 21, dose_logs/par-d3: postgres %s', pg_temp.parity_row('dose_logs', 'par-d3'));
end $$;

-- Step 22: and brings the cascaded dose back with a note: stored deleted
begin;
insert into parity_now values (22, now());
update public.dose_logs set deleted_at = null, notes = 'after food', write_id = '00000000-0000-0000-0000-000000000014', edited_at = '2020-05-01T00:00:00.000Z', field_edited_at = '{"notes":{"at":"2020-05-01T00:00:00.000Z","auto":false}}'::jsonb
  where id = 'par-d1';
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d1') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"2020-05-01T00:00:00.000Z","auto":false},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"2020-04-01T00:00:00.000Z","auto":false},"taken_time":{"at":"2020-04-01T00:00:00.000Z","auto":false}},"row_version":4,"updated_at":"@20","write_id":true}'::jsonb,
    format('parity step 22, dose_logs/par-d1: postgres %s', pg_temp.parity_row('dose_logs', 'par-d1'));
end $$;

-- Step 23: 0.3.0 skips a cascaded dose: brought back, then deleted with its parent again
begin;
insert into parity_now values (23, now());
insert into public.dose_logs (id, prescription_id, scheduled_time, status, notes, updated_at)
  values ('par-d2', 'par-p1', '2020-01-01T16:00:00.000Z', 'skipped', 'n', '2020-05-01T00:00:00.000Z')
  on conflict (id) do update set prescription_id = excluded.prescription_id, scheduled_time = excluded.scheduled_time, status = excluded.status, notes = excluded.notes, updated_at = excluded.updated_at;
commit;
do $$ begin
  assert pg_temp.parity_row('dose_logs', 'par-d2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"notes":{"at":"@18","auto":false},"prescription_id":{"at":"1970-01-01T00:00:00.000Z","auto":true},"scheduled_time":{"at":"1970-01-01T00:00:00.000Z","auto":true},"status":{"at":"@23","auto":false},"taken_time":{"at":"@19","auto":false}},"row_version":6,"updated_at":"@23","write_id":false}'::jsonb,
    format('parity step 23, dose_logs/par-d2: postgres %s', pg_temp.parity_row('dose_logs', 'par-d2'));
end $$;

-- Step 24: a prescription sent under the deleted treatment: stored deleted
begin;
insert into parity_now values (24, now());
insert into public.prescriptions (id, treatment_id, medication_id, dosage, start_time, write_id, edited_at, field_edited_at)
  values ('par-p2', 'par-t1', 'par-m1', '2 tablets', '2020-05-02T08:00:00.000Z', '00000000-0000-0000-0000-000000000015', '2020-05-01T00:00:00.000Z', '{}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('prescriptions', 'par-p2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{},"row_version":1,"updated_at":"@24","write_id":true}'::jsonb,
    format('parity step 24, prescriptions/par-p2: postgres %s', pg_temp.parity_row('prescriptions', 'par-p2'));
end $$;

-- Step 25: 0.6.0 inserts a prescription document
begin;
insert into parity_now values (25, now());
insert into public.rx (id, user_id, kind, issued_on, write_id, edited_at, field_edited_at)
  values ('par-rx1', '00000000-0000-0000-0000-00000000000a', 'ssn', '2020-05-01', '00000000-0000-0000-0000-000000000016', '2020-05-01T00:00:00.000Z', '{"kind":{"at":"2020-05-01T00:00:00.000Z","auto":false}}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('rx', 'par-rx1') = '{"deleted":false,"edited_at":"2020-05-01T00:00:00.000Z","field_edited_at":{"kind":{"at":"2020-05-01T00:00:00.000Z","auto":false}},"row_version":1,"updated_at":"@25","write_id":true}'::jsonb,
    format('parity step 25, rx/par-rx1: postgres %s', pg_temp.parity_row('rx', 'par-rx1'));
end $$;

-- Step 26: and a dispensing of it
begin;
insert into parity_now values (26, now());
insert into public.rx_dispensings (id, user_id, rx_id, item_id, packs, dispensed_on, write_id, edited_at, field_edited_at)
  values ('par-rxd1', '00000000-0000-0000-0000-00000000000a', 'par-rx1', 'i1', 1, '2020-05-02', '00000000-0000-0000-0000-000000000017', '2020-05-01T00:00:00.000Z', '{"packs":{"at":"2020-05-01T00:00:00.000Z","auto":false}}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('rx_dispensings', 'par-rxd1') = '{"deleted":false,"edited_at":"2020-05-01T00:00:00.000Z","field_edited_at":{"packs":{"at":"2020-05-01T00:00:00.000Z","auto":false}},"row_version":1,"updated_at":"@26","write_id":true}'::jsonb,
    format('parity step 26, rx_dispensings/par-rxd1: postgres %s', pg_temp.parity_row('rx_dispensings', 'par-rxd1'));
end $$;

-- Step 27: a person deletes the prescription: the tombstone cascades to its dispensing as the app's own change
begin;
insert into parity_now values (27, now());
update public.rx set deleted_at = '2020-05-01T00:00:00.000Z', write_id = '00000000-0000-0000-0000-000000000018', edited_at = '2020-05-01T00:00:00.000Z'
  where id = 'par-rx1';
commit;
do $$ begin
  assert pg_temp.parity_row('rx', 'par-rx1') = '{"deleted":true,"edited_at":"2020-05-01T00:00:00.000Z","field_edited_at":{"kind":{"at":"2020-05-01T00:00:00.000Z","auto":false}},"row_version":2,"updated_at":"@27","write_id":true}'::jsonb,
    format('parity step 27, rx/par-rx1: postgres %s', pg_temp.parity_row('rx', 'par-rx1'));
  assert pg_temp.parity_row('rx_dispensings', 'par-rxd1') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"packs":{"at":"2020-05-01T00:00:00.000Z","auto":false}},"row_version":2,"updated_at":"@27","write_id":false}'::jsonb,
    format('parity step 27, rx_dispensings/par-rxd1: postgres %s', pg_temp.parity_row('rx_dispensings', 'par-rxd1'));
end $$;

-- Step 28: a device that has not heard of it sends a dispensing: stored deleted
begin;
insert into parity_now values (28, now());
insert into public.rx_dispensings (id, user_id, rx_id, item_id, packs, dispensed_on, write_id, edited_at, field_edited_at)
  values ('par-rxd2', '00000000-0000-0000-0000-00000000000a', 'par-rx1', 'i1', 1, '2020-05-03', '00000000-0000-0000-0000-000000000019', '2020-05-01T00:00:00.000Z', '{"packs":{"at":"2020-05-01T00:00:00.000Z","auto":false}}'::jsonb)
  on conflict (id) do nothing;
commit;
do $$ begin
  assert pg_temp.parity_row('rx_dispensings', 'par-rxd2') = '{"deleted":true,"edited_at":"1970-01-01T00:00:00.000Z","field_edited_at":{"packs":{"at":"2020-05-01T00:00:00.000Z","auto":false}},"row_version":1,"updated_at":"@28","write_id":true}'::jsonb,
    format('parity step 28, rx_dispensings/par-rxd2: postgres %s', pg_temp.parity_row('rx_dispensings', 'par-rxd2'));
end $$;

select 'fake server parity passed' as result;
