project_id = "medora"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
